macro(parse_version_string PKG_NAME)
    string(REPLACE "." ";" _TMP_VERSION_LIST ${${PKG_NAME}_VERSION})
    list(LENGTH _TMP_VERSION_LIST ${PKG_NAME}_VERSION_COUNT)
    if(${PKG_NAME}_VERSION_COUNT GREATER 0)
        list(GET _TMP_VERSION_LIST 0 ${PKG_NAME}_VERSION_MAJOR)
        if(${PKG_NAME}_VERSION_COUNT GREATER 1)
            list(GET _TMP_VERSION_LIST 1 ${PKG_NAME}_VERSION_MINOR)
            if(${PKG_NAME}_VERSION_COUNT GREATER 2)
                list(GET _TMP_VERSION_LIST 2 ${PKG_NAME}_VERSION_PATCH)
                if(${PKG_NAME}_VERSION_COUNT GREATER 3)
                    list(GET _TMP_VERSION_LIST 3 ${PKG_NAME}_VERSION_TWEAK)
                endif()
            endif()
        endif()
    endif()
    unset(_TMP_VERSION_LIST)
endmacro()

